server:
  port: 8080

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/hrms
    username: postgres

  cloudinary:
    cloud-name: "${cloud.name}"
    api-key: "${cloud.api.key}"
    api-secret: "${cloud.api.secret}"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/hrms
    username: postgres
---

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    password: postgres
    url: jdbc:postgresql://hrms-pg-server:5432/hrms
    username: postgres